### ISSUE TITLE
Switch on authentication

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/ArangoDBStarter#10]
We need a procedure to run a cluster with authentication, possibly by documenting how the user has to edit the configuration files. I will investigate how to do this in the simplest way.

**Comment by neunhoef** [comment]
I did some investigation towards this goal: We need to make the starter refrain from putting `--server.authentication false` on the command line of servers. Rather, it should not put this option on the command line, but put ```
[server]
authentication = false
``` in the configuration files. Then the user can (after starting the cluster), change the `false` to `true` in all configuration files and add the option
```
[server]
jwt-secret = abcdefgh
```
to all configuration files and simply restart the cluster.

**Comment by ewoutp** [comment]
Fixed in #18

**Comment by dsonet** [comment]
@neunhoef @ewoutp 
Hi guys I need help on this.
Since I have 3 nodes, so I updated all 9 arangod.conf files.
Made sure they all have this:
```
[server]
authentication = true
jwt-secret = thesamekeyinallfiles
```

But after I restarted my cluster, after awhile, I got:
`Failed to get master URL, retrying in 5sec (ArangoError: Code 401, ErrorNum 0)`
Am I missing something and what can I do for this?

**Comment by dsonet** [comment]
OK. Figure it out finally. Not only need to update these files, but also in `setup.json`.
