### ISSUE TITLE
PortOffset 0 on multiple servers

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/ArangoDBStarter#3]
A customer wanted to use the starter on Windows (irrelevant here) to setup an ArangoDB cluster on multiple machines. They would prefer it if one could make it so that the same ports are used for starter, agent, coordinator (in particular) and dbserver on all machines. Maybe we can detect this automatically, and if this does not work reliably, there should at least be an option in the starter to override the automatic increment of the portOffset and force it to be zero.

**Comment by neunhoef** [comment]
Related question: If we allow this, can we migrate a previously started cluster with port offset to one offset zero without a complete reinstall.

**Comment by ewoutp** [comment]
Currently a `portOffset` is allocated based on the next free offset.
We can change this to the next free `portOffset+slaveAddress` pair.

However since we can pre-allocate port offsets, and currently a `portOffset` is only linked to a slave ID, we must forbid that you change the address of a slave after you've pre-allocated a port offset.

Not sure if that leads to new problems.

**Comment by ewoutp** [comment]
The second issue (migrating clusters from one portOffset scheme to another) would require:

- Different arangodb-starter config files 
- Different arangod server config files 
- Different arangod server system tables (guessing)

To me this sounds like adding a LOT of complexity for a very small edge case.

**Comment by neunhoef** [comment]
I see, migration is too complex, so we do not support it. I would be in favour of allocating the next free portOffset+slaveAddress pair.
