### ISSUE TITLE
Task manager "stop task" in Windows seems to kill ArangoDBStarter

### ISSUE THREAD

**Issue by neunhoef** [arangodb-helper/ArangoDBStarter#5]
Stopping the starter with Control-C in a cmd.exe leads to a proper shutdown. But killing the starter in the task manager seems to terminate it immediately and the subprocesses arangod.exe keep running. Maybe we can handle further signals or events on Windows.

**Comment by ewoutp** [comment]
A kill using the windows task manager is really a kill. This is not something we can catch.
See also http://stackoverflow.com/questions/20054471/how-to-detect-program-java-force-to-close-from-windows-task-manager?answertab=votes#tab-top.

I'm closing this since:
a) we cannot fix it,
b) there are 2 proper ways to do a shutdown (Control-C & shutdown REST api)
